export type WalkthroughAdvance = 'click-target' | 'next-button';

export interface WalkthroughRichInstruction {
  readonly lead: string;
  readonly code: string;
  readonly explanation?: string;
  readonly learnMore?: {
    readonly label: string;
    readonly href: string;
  };
}

export type WalkthroughInstruction = string | WalkthroughRichInstruction;

export type WalkthroughTarget =
  | { readonly kind: 'action-tab'; readonly id: string }
  | { readonly kind: 'action'; readonly id: string }
  | { readonly kind: 'command'; readonly id: string }
  | { readonly kind: 'discover-tab'; readonly id: string }
  | { readonly kind: 'sheet'; readonly id: string }
  | { readonly kind: 'grid-column'; readonly id: string }
  | { readonly kind: 'field'; readonly id: string }
  | { readonly kind: 'view'; readonly id: string }
  | { readonly kind: 'element'; readonly id: string }
  | { readonly kind: 'tour'; readonly id: string }
  | { readonly kind: 'local-endpoint'; readonly label: string; readonly part: 'row' | 'guidance' }
  | { readonly kind: 'completed-run'; readonly target: WalkthroughTarget };

export interface WalkthroughStep {
  readonly id: string;
  readonly title: string;
  readonly instruction: WalkthroughInstruction;
  readonly target: WalkthroughTarget;
  readonly expected?: string;
  readonly advance: WalkthroughAdvance;
}

export interface WalkthroughDefinition {
  readonly id: string;
  readonly title: string;
  readonly description: string;
  readonly requirements?: string;
  /** Omitted means visible in every edition. */
  readonly editions?: readonly string[];
  readonly steps: readonly WalkthroughStep[];
}

export const REGEX_EXTRACT_WALKTHROUGH: WalkthroughDefinition = {
  id: 'regex-extract',
  title: 'Follow contracts across sheets',
  description: 'Extract contract IDs from stories, join them to contract records, and inspect the unmatched rows.',
  steps: [
    {
      id: 'open-dispatches',
      title: 'Open Dispatches',
      instruction: 'Click Dispatches so the extraction starts from the story sheet.',
      target: { kind: 'sheet', id: 'Dispatches' },
      expected: 'The 24 civic stories appear.',
      advance: 'click-target',
    },
    {
      id: 'open-dispatches-grid',
      title: 'Start in Grid',
      instruction: 'Click Grid so new columns will be visible as they populate.',
      target: { kind: 'view', id: 'grid' },
      advance: 'click-target',
    },
    {
      id: 'inspect-story-column',
      title: 'Read the source stories',
      instruction: 'Look down the story column and read a few entries. They range from short tips to detailed reports; this is the source text the regex extractor will search.',
      target: { kind: 'grid-column', id: 'story' },
      expected: 'You can see recurring people, agencies, amounts, and contract IDs inside the reporting text.',
      advance: 'next-button',
    },
    {
      id: 'open-extract',
      title: 'Open Analyze',
      instruction: 'Click Analyze and find the Extract group of actions.',
      target: { kind: 'action-tab', id: 'analyze' },
      expected: 'The Analyze and Extract action groups appear.',
      advance: 'click-target',
    },
    {
      id: 'open-regex',
      title: 'Choose Extract text with regex',
      instruction: 'Click Extract text with regex. This action finds text that matches a repeatable pattern.',
      target: { kind: 'action', id: 'map.regex_extract' },
      expected: 'The Extract text with regex form opens.',
      advance: 'click-target',
    },
    {
      id: 'choose-source',
      title: 'Choose the source text',
      instruction: 'Choose the story column. Regex will search each story independently.',
      target: { kind: 'field', id: 'field-input_columns' },
      advance: 'next-button',
    },
    {
      id: 'enter-pattern',
      title: 'Enter the contract pattern',
      instruction: 'Enter \\bCTR-\\d{4}-\\d{3}\\b to match IDs such as CTR-2026-014.',
      target: { kind: 'field', id: 'field-pattern' },
      expected: 'The form accepts the pattern without an error.',
      advance: 'next-button',
    },
    {
      id: 'name-output',
      title: 'Name the result column',
      instruction: 'Set Save to to contract_id so the extracted values have a clear home.',
      target: { kind: 'field', id: 'field-output-extracted' },
      advance: 'next-button',
    },
    {
      id: 'run-action',
      title: 'Run the action',
      instruction: 'Click Run. If it is disabled, check that the pattern and output name are filled in.',
      target: { kind: 'field', id: 'generated-action-run' },
      expected: 'The action starts and the form closes.',
      advance: 'click-target',
    },
    {
      id: 'review-results',
      title: 'Review the extracted IDs',
      instruction: 'Look across the grid for the new contract_id column as its values populate.',
      target: { kind: 'completed-run', target: { kind: 'element', id: 'grid' } },
      expected: 'Stories with a contract reference receive an extracted ID; other rows stay empty.',
      advance: 'next-button',
    },
    {
      id: 'open-analyze',
      title: 'Open Tables',
      instruction: 'Click Tables to find actions that reshape and join sheets.',
      target: { kind: 'action-tab', id: 'tables' },
      expected: 'The Tables actions appear.',
      advance: 'click-target',
    },
    {
      id: 'open-join',
      title: 'Choose Join sheets',
      instruction: 'Click Join sheets (by key). This creates a new sheet from matching values.',
      target: { kind: 'action', id: 'derive.join' },
      expected: 'The deterministic join form opens.',
      advance: 'click-target',
    },
    {
      id: 'choose-right-sheet',
      title: 'Join to Contracts',
      instruction: 'Keep Dispatches on the left and choose Contracts on the right.',
      target: { kind: 'field', id: 'field-join_right_sheet' },
      advance: 'next-button',
    },
    {
      id: 'choose-left-key',
      title: 'Choose the Dispatches key',
      instruction: 'Choose contract_id as the left key.',
      target: { kind: 'field', id: 'field-join_key_left-0' },
      advance: 'next-button',
    },
    {
      id: 'choose-right-key',
      title: 'Choose the Contracts key',
      instruction: 'Choose contract_id as the right key too. Equal IDs will now match.',
      target: { kind: 'field', id: 'field-join_key_right-0' },
      advance: 'next-button',
    },
    {
      id: 'choose-outer-join',
      title: 'Keep matched and unmatched rows',
      instruction: 'Choose Keep all rows (outer) so the result also shows stories without IDs and contracts never mentioned.',
      target: { kind: 'field', id: 'field-how' },
      advance: 'next-button',
    },
    {
      id: 'enable-indicator',
      title: 'Show which side each row came from',
      instruction: "Turn on Include a 'which side' column. This makes gaps easy to filter.",
      target: { kind: 'field', id: 'field-join_indicator' },
      advance: 'click-target',
    },
    {
      id: 'name-join',
      title: 'Name the joined sheet',
      instruction: {
        lead: 'Name the new sheet',
        code: 'Contract trail',
      },
      target: { kind: 'field', id: 'field-sheet_name' },
      advance: 'next-button',
    },
    {
      id: 'run-join',
      title: 'Create the joined sheet',
      instruction: 'Click Run to materialize the join.',
      target: { kind: 'field', id: 'generated-action-run' },
      expected: 'Frisket opens a new derived sheet.',
      advance: 'click-target',
    },
    {
      id: 'review-join',
      title: 'Inspect the contract trail',
      instruction: 'Use the indicator column to find story-only and contract-only rows, then inspect the matched vendor and agency details.',
      // Joins materialize atomically and navigate to the finished sheet; unlike
      // row actions they do not expose run progress in the status bar.
      target: { kind: 'element', id: 'grid' },
      expected: 'The result preserves matches as well as leads that need follow-up.',
      advance: 'next-button',
    },
  ],
};

export const LAWSUIT_DOCUMENT_WALKTHROUGH: WalkthroughDefinition = {
  id: 'lawsuit-documents',
  title: 'Read a stack of lawsuit PDFs',
  description: 'Inspect the original filings, convert them to text, and extract reusable case facts.',
  requirements: 'Requires an available PDF-to-Markdown engine and model provider.',
  steps: [
    {
      id: 'open-filings',
      title: 'Open the filings',
      instruction: 'Click Court filings. Each row contains one synthetic lawsuit PDF.',
      target: { kind: 'sheet', id: 'Court filings' },
      advance: 'click-target',
    },
    {
      id: 'open-document-view',
      title: 'Switch to Document view',
      instruction: 'Click Document to review PDFs as source documents rather than grid cells.',
      target: { kind: 'view', id: 'document' },
      expected: 'The selected filing opens with a document list beside it.',
      advance: 'click-target',
    },
    {
      id: 'inspect-pdf',
      title: 'Inspect the source',
      instruction: 'Read a page and notice the case number, parties, claims, and requested relief. These are allegations, not established facts.',
      target: { kind: 'element', id: 'document-pdf' },
      advance: 'next-button',
    },
    {
      id: 'open-read',
      title: 'Open Media',
      instruction: 'Click Media and find the Documents group with OCR, Markdown, and PDF tools.',
      target: { kind: 'action-tab', id: 'media' },
      advance: 'click-target',
    },
    {
      id: 'open-to-markdown',
      title: 'Choose To Markdown',
      instruction: 'Click To Markdown to turn each searchable PDF into analysis-ready text.',
      target: { kind: 'action', id: 'media.to_markdown' },
      advance: 'click-target',
    },
    {
      id: 'choose-pdf-source',
      title: 'Use the PDF file column',
      instruction: 'Choose media as the source column.',
      target: { kind: 'field', id: 'field-source' },
      advance: 'next-button',
    },
    {
      id: 'choose-converter',
      title: 'Choose an available converter',
      instruction: 'Choose an available conversion engine. Searchable PDFs do not need OCR.',
      target: { kind: 'field', id: 'engine-picker-button' },
      advance: 'next-button',
    },
    {
      id: 'name-filing-text',
      title: 'Name the text column',
      instruction: 'Set Save to to filing_text.',
      target: { kind: 'field', id: 'field-output-markdown' },
      advance: 'next-button',
    },
    {
      id: 'open-grid',
      title: 'Return to Grid before running',
      instruction: 'Click Grid now so you can watch filing_text appear beside each PDF.',
      target: { kind: 'view', id: 'grid' },
      advance: 'click-target',
    },
    {
      id: 'run-conversion',
      title: 'Convert the filings',
      instruction: 'Click Run to convert all six PDFs.',
      target: { kind: 'field', id: 'generated-action-run' },
      expected: 'The filing_text column begins to populate in the grid.',
      advance: 'click-target',
    },
    {
      id: 'review-filing-text',
      title: 'Review the converted text',
      instruction: 'Review filing_text in Grid. The converted text is ready for extraction; the source PDFs remain available in Document.',
      target: { kind: 'completed-run', target: { kind: 'element', id: 'grid' } },
      advance: 'next-button',
    },
    {
      id: 'open-extract-case',
      title: 'Open Analyze',
      instruction: 'Click Analyze and find the Extract group; next we will pull the court case number from every filing.',
      target: { kind: 'action-tab', id: 'analyze' },
      advance: 'click-target',
    },
    {
      id: 'open-regex-case',
      title: 'Choose Extract text with regex',
      instruction: 'Click Extract text with regex.',
      target: { kind: 'action', id: 'map.regex_extract' },
      advance: 'click-target',
    },
    {
      id: 'choose-filing-text',
      title: 'Search the filing text',
      instruction: 'Choose filing_text as the source column.',
      target: { kind: 'field', id: 'text-source-column-select' },
      advance: 'next-button',
    },
    {
      id: 'enter-case-pattern',
      title: 'Enter the case-number pattern',
      instruction: {
        lead: 'Enter',
        code: 'RV-CV-\\d{4}-\\d{5}',
        explanation: 'This is a regular expression. It means RV-CV-(four digits)-(five digits).',
        learnMore: {
          label: 'Learn more about regular expressions',
          href: 'https://docs.python.org/3/howto/regex.html',
        },
      },
      target: { kind: 'field', id: 'field-pattern' },
      advance: 'next-button',
    },
    {
      id: 'name-case-number',
      title: 'Name the extracted value',
      instruction: 'Set Save to to case_number.',
      target: { kind: 'field', id: 'new-column-name' },
      advance: 'next-button',
    },
    {
      id: 'preview-case-extraction',
      title: 'Preview the case numbers',
      instruction: 'Click Preview. The sample values will appear in the case_number column while the action pane stays open for adjustments.',
      target: { kind: 'field', id: 'preview-button' },
      advance: 'click-target',
    },
    {
      id: 'run-case-extraction',
      title: 'Keep the extracted case numbers',
      instruction: 'Check the previewed case_number values in Grid, then click Run for real to extract them from every filing.',
      target: { kind: 'element', id: 'preview-run-for-real-button' },
      advance: 'click-target',
    },
    {
      id: 'review-case-numbers',
      title: 'Review the exact matches',
      instruction: 'Confirm that all six filings received a case number. Regex is a good fit here because every case number follows the same visible pattern.',
      target: { kind: 'completed-run', target: { kind: 'element', id: 'grid' } },
      expected: 'Every filing receives one case number that can be checked against its source PDF.',
      advance: 'next-button',
    },
    {
      id: 'return-to-extract-facts',
      title: 'Return to Analyze',
      instruction: 'Click Analyze and return to the Extract group. This time we will pull facts whose wording varies from filing to filing.',
      target: { kind: 'action-tab', id: 'analyze' },
      advance: 'click-target',
    },
    {
      id: 'open-structured-extract',
      title: 'Choose Extract fields',
      instruction: 'Click Extract fields to create several structured columns with one model call per filing.',
      target: { kind: 'action', id: 'map.extract' },
      advance: 'click-target',
    },
    {
      id: 'choose-structured-source',
      title: 'Read the converted filing',
      instruction: 'Choose filing_text as the source column.',
      target: { kind: 'field', id: 'text-source-column-select' },
      advance: 'next-button',
    },
    {
      id: 'define-filing-fields',
      title: 'Define the filing facts',
      instruction: 'Replace the three default output names with plaintiff, defendant, and requested_relief. Keep them as Text fields and describe the last one as the remedy the plaintiff asks the court to order.',
      target: { kind: 'field', id: 'output-fields-label' },
      advance: 'next-button',
    },
    {
      id: 'set-filing-extraction-prompt',
      title: 'Set the extraction rules',
      instruction: 'Ask for the plaintiff and defendant exactly as filed and a one-sentence description of the requested relief. Tell the model to leave a field blank rather than infer a missing value.',
      target: { kind: 'field', id: 'action-prompt' },
      advance: 'next-button',
    },
    {
      id: 'choose-filing-model',
      title: 'Choose a model',
      instruction: 'Choose an available model for structured extraction.',
      target: { kind: 'field', id: 'model-picker-button' },
      advance: 'next-button',
    },
    {
      id: 'run-filing-extraction',
      title: 'Extract the filing facts',
      instruction: 'Click Run to fill all three columns for every filing.',
      target: { kind: 'field', id: 'run-button' },
      expected: 'Plaintiff, defendant, and requested relief populate beside each filing.',
      advance: 'click-target',
    },
    {
      id: 'review-filing-facts',
      title: 'Compare the cases',
      instruction: 'Scan the three new columns across all six rows. Use the original PDFs when a value looks surprising; extracted allegations still require reporting and verification.',
      target: { kind: 'completed-run', target: { kind: 'element', id: 'grid' } },
      expected: 'The filings now have both a deterministic join key and comparable model-extracted facts.',
      advance: 'next-button',
    },
  ],
};

export const COUNCIL_AUDIO_WALKTHROUGH: WalkthroughDefinition = {
  id: 'council-audio',
  title: 'Listen through council meetings',
  description: 'Play rights-cleared meeting excerpts, transcribe them, and review time-aligned text.',
  requirements: 'Requires an available speech-to-text engine and model provider.',
  steps: [
    {
      id: 'open-council-audio',
      title: 'Open the meeting audio',
      instruction: 'Click Council audio. The two rows are local five-minute excerpts with source metadata in the Council meetings sheet.',
      target: { kind: 'sheet', id: 'Council audio' },
      advance: 'click-target',
    },
    {
      id: 'open-audio-document-view',
      title: 'Switch to Document view',
      instruction: 'Click Document to work with the recordings as playable source material.',
      target: { kind: 'view', id: 'document' },
      advance: 'click-target',
    },
    {
      id: 'play-audio',
      title: 'Listen to the source',
      instruction: 'Play part of the selected excerpt. One meeting discusses policy and lobbying; the other discusses police oversight.',
      target: { kind: 'element', id: 'document-audio' },
      expected: 'The audio plays locally without relying on YouTube or another remote host.',
      advance: 'next-button',
    },
    {
      id: 'open-audio-read',
      title: 'Open Media',
      instruction: 'Click Media and find the Transcripts group with transcription and topic tools.',
      target: { kind: 'action-tab', id: 'media' },
      advance: 'click-target',
    },
    {
      id: 'open-transcribe',
      title: 'Choose Transcribe',
      instruction: 'Click Transcribe to create searchable, time-aligned text.',
      target: { kind: 'action', id: 'media.transcribe' },
      advance: 'click-target',
    },
    {
      id: 'choose-audio-source',
      title: 'Use the audio column',
      instruction: 'Choose media as the source column.',
      target: { kind: 'field', id: 'field-source' },
      advance: 'next-button',
    },
    {
      id: 'choose-transcription-engine',
      title: 'Choose a transcription engine',
      instruction: 'Open the engine picker and choose an available local, sidecar, or hosted speech-to-text engine.',
      target: { kind: 'field', id: 'engine-picker-button' },
      advance: 'next-button',
    },
    {
      id: 'name-transcript',
      title: 'Name the transcript',
      instruction: 'Name the transcript column transcript. You can name the timestamped segments separately.',
      target: { kind: 'field', id: 'field-output-text' },
      advance: 'next-button',
    },
    {
      id: 'review-transcripts-grid',
      title: 'Return to Grid before running',
      instruction: 'Click Grid now so you can watch transcript and segments populate. Engines that detect language also add that output.',
      target: { kind: 'view', id: 'grid' },
      advance: 'click-target',
    },
    {
      id: 'run-transcription',
      title: 'Transcribe both excerpts',
      instruction: 'Click Run and let the transcription finish.',
      target: { kind: 'field', id: 'generated-action-run' },
      expected: 'Transcript text and timestamped segments populate for each recording.',
      advance: 'click-target',
    },
    {
      id: 'review-audio-transcripts',
      title: 'Review the transcripts',
      instruction: 'Read the completed transcript column, then open the recording and its timestamps together.',
      target: { kind: 'completed-run', target: { kind: 'element', id: 'grid' } },
      expected: 'Each generated transcript remains connected to its original recording and timestamps.',
      advance: 'next-button',
    },
    {
      id: 'open-timed-transcript',
      title: 'Open the timed transcript',
      instruction: 'Click Document. The recording and its completed transcript now share one reading surface.',
      target: { kind: 'completed-run', target: { kind: 'view', id: 'document' } },
      advance: 'click-target',
    },
    {
      id: 'review-timed-transcript',
      title: 'Jump between audio and text',
      instruction: 'Click a timestamped phrase to seek the recording to that moment. Use this view to spot-check a name, quotation, decision, or deadline.',
      target: { kind: 'element', id: 'document-temporal-transcript' },
      expected: 'The player and transcript stay together while the active phrase follows playback.',
      advance: 'next-button',
    },
    {
      id: 'return-audio-grid',
      title: 'Return to Grid',
      instruction: 'Click Grid before creating the meeting brief so you can see the new column fill in.',
      target: { kind: 'view', id: 'grid' },
      advance: 'click-target',
    },
    {
      id: 'open-audio-analyze',
      title: 'Open Analyze',
      instruction: 'Click Analyze to turn each long transcript into a deadline-focused meeting brief.',
      target: { kind: 'action-tab', id: 'analyze' },
      advance: 'click-target',
    },
    {
      id: 'open-audio-summarize',
      title: 'Choose Summarize',
      instruction: 'Click Summarize.',
      target: { kind: 'action', id: 'map.summarize' },
      advance: 'click-target',
    },
    {
      id: 'choose-transcript-source',
      title: 'Summarize the transcript',
      instruction: 'Choose transcript as the source column.',
      target: { kind: 'field', id: 'text-source-columns' },
      advance: 'next-button',
    },
    {
      id: 'focus-meeting-summary',
      title: 'Focus on what just happened',
      instruction: 'Ask for two sentences naming the decision, money involved, and any deadline or next step.',
      target: { kind: 'field', id: 'field-instruction' },
      advance: 'next-button',
    },
    {
      id: 'name-meeting-brief',
      title: 'Name the meeting brief',
      instruction: {
        lead: 'Set Save to to',
        code: 'meeting_brief',
      },
      target: { kind: 'field', id: 'field-output-summary' },
      advance: 'next-button',
    },
    {
      id: 'run-meeting-summary',
      title: 'Create both meeting briefs',
      instruction: 'Click Run.',
      target: { kind: 'field', id: 'generated-action-run' },
      expected: 'A concise meeting_brief populates beside each full transcript.',
      advance: 'click-target',
    },
    {
      id: 'finish-audio-review',
      title: 'Compare the urgent details',
      instruction: 'Compare the two meeting_brief values and use the timestamps in the source transcript to verify the decision, amount, or deadline you would report first.',
      target: { kind: 'completed-run', target: { kind: 'element', id: 'grid' } },
      expected: 'You have a short, reviewable triage column without losing the complete transcript or source audio.',
      advance: 'next-button',
    },
  ],
};

export const CIVIC_AI_TRIAGE_WALKTHROUGH: WalkthroughDefinition = {
  id: 'civic-ai-triage',
  title: 'Triage civic stories with AI',
  description: 'Find entities, summarize each story, categorize it, and identify the next fact to verify.',
  requirements: 'Requires an available named-entity engine and model provider.',
  steps: [
    {
      id: 'open-dispatches',
      title: 'Open Dispatches',
      instruction: 'Click Dispatches. The stories vary from short tips to detailed records analyses.',
      target: { kind: 'sheet', id: 'Dispatches' },
      advance: 'click-target',
    },
    {
      id: 'open-ai-grid',
      title: 'Start in Grid',
      instruction: 'Click Grid so generated columns remain visible while actions run.',
      target: { kind: 'view', id: 'grid' },
      advance: 'click-target',
    },
    {
      id: 'open-entity-extract',
      title: 'Open Analyze',
      instruction: 'Click Analyze and find the Extract group with entity actions.',
      target: { kind: 'action-tab', id: 'analyze' },
      advance: 'click-target',
    },
    {
      id: 'open-ner',
      title: 'Choose Named entities',
      instruction: 'Click Named entities to annotate people, organizations, places, dates, and money in the source text.',
      target: { kind: 'action', id: 'map.ner' },
      advance: 'click-target',
    },
    {
      id: 'choose-ner-engine',
      title: 'Choose an entity engine',
      instruction: 'Choose an available engine. The local spaCy option is a good fit for this walkthrough.',
      target: { kind: 'field', id: 'engine-picker-button' },
      advance: 'next-button',
    },
    {
      id: 'choose-ner-source',
      title: 'Choose specific source columns',
      instruction: 'Under Read text from, click Column(s).',
      target: { kind: 'field', id: 'ner-source-mode-columns' },
      advance: 'click-target',
    },
    {
      id: 'choose-ner-story-column',
      title: 'Read entities from story',
      instruction: 'Open the column picker and select only story.',
      target: { kind: 'field', id: 'ner-source-columns' },
      advance: 'next-button',
    },
    {
      id: 'run-ner',
      title: 'Extract the entities',
      instruction: 'Click Run to annotate the selected story text.',
      target: { kind: 'field', id: 'run-button' },
      expected: 'Entity annotations are added without replacing the original story.',
      advance: 'click-target',
    },
    {
      id: 'open-annotated-document',
      title: 'Read the annotations in context',
      instruction: 'Click Document to inspect highlighted entities in the full story.',
      target: { kind: 'completed-run', target: { kind: 'view', id: 'document' } },
      advance: 'click-target',
    },
    {
      id: 'inspect-annotations',
      title: 'Inspect names in context',
      instruction: 'Review several highlights and confirm the entity type against the surrounding sentence.',
      target: { kind: 'element', id: 'annotated-text-reader' },
      expected: 'The story remains readable while its extracted entities become reviewable evidence.',
      advance: 'next-button',
    },
    {
      id: 'return-to-ai-grid',
      title: 'Return to Grid',
      instruction: 'Click Grid before the next actions so summaries, topics, and follow-up checks appear as columns.',
      target: { kind: 'view', id: 'grid' },
      advance: 'click-target',
    },
    {
      id: 'open-analyze-summary',
      title: 'Open Analyze',
      instruction: 'Click Analyze to move from extraction to story triage.',
      target: { kind: 'action-tab', id: 'analyze' },
      advance: 'click-target',
    },
    {
      id: 'open-summarize',
      title: 'Choose Summarize',
      instruction: 'Click Summarize.',
      target: { kind: 'action', id: 'map.summarize' },
      advance: 'click-target',
    },
    {
      id: 'choose-summary-source',
      title: 'Summarize the story body',
      instruction: 'Choose story as the source column.',
      target: { kind: 'field', id: 'text-source-columns' },
      advance: 'next-button',
    },
    {
      id: 'edit-summary-prompt',
      title: 'Set the summary instruction',
      instruction: 'Optionally add a custom instruction, such as leading with the action and ending with the unresolved question.',
      target: { kind: 'field', id: 'field-instruction' },
      advance: 'next-button',
    },
    {
      id: 'name-summary',
      title: 'Name the summary column',
      instruction: 'Set Save to to summary.',
      target: { kind: 'field', id: 'field-output-summary' },
      advance: 'next-button',
    },
    {
      id: 'run-summary',
      title: 'Summarize every story',
      instruction: 'Click Run.',
      target: { kind: 'field', id: 'generated-action-run' },
      expected: 'A compact summary populates beside each raw story.',
      advance: 'click-target',
    },
    {
      id: 'open-extract-classify',
      title: 'Return to Analyze',
      instruction: 'Click Analyze for the classification step.',
      target: { kind: 'completed-run', target: { kind: 'action-tab', id: 'analyze' } },
      advance: 'click-target',
    },
    {
      id: 'open-classify',
      title: 'Choose Classify',
      instruction: 'Click Classify to assign one consistent label per story.',
      target: { kind: 'action', id: 'map.classify' },
      advance: 'click-target',
    },
    {
      id: 'choose-classify-source',
      title: 'Classify the story body',
      instruction: 'Choose story as the source.',
      target: { kind: 'field', id: 'classify-source-column-select' },
      advance: 'next-button',
    },
    {
      id: 'set-civic-labels',
      title: 'Choose the story categories',
      instruction: {
        lead: 'Enter labels that fit this project, such as',
        code: 'housing, courts, public safety, contracts, health, transit, education, environment, other',
      },
      target: { kind: 'field', id: 'classify-labels' },
      advance: 'next-button',
    },
    {
      id: 'name-topic',
      title: 'Name the category column',
      instruction: 'Set Save to to topic.',
      target: { kind: 'field', id: 'new-column-name' },
      advance: 'next-button',
    },
    {
      id: 'run-classify',
      title: 'Categorize the stories',
      instruction: 'Click Run.',
      target: { kind: 'field', id: 'run-button' },
      expected: 'Each story receives one comparable topic label.',
      advance: 'click-target',
    },
    {
      id: 'open-analyze-ask',
      title: 'Return to Analyze',
      instruction: 'Click Analyze for one final reporting question.',
      target: { kind: 'completed-run', target: { kind: 'action-tab', id: 'analyze' } },
      advance: 'click-target',
    },
    {
      id: 'open-ask',
      title: 'Choose Ask',
      instruction: 'Click Ask to pose the same question to every row.',
      target: { kind: 'action', id: 'map.ask' },
      advance: 'click-target',
    },
    {
      id: 'choose-ask-source',
      title: 'Ask about the story',
      instruction: 'Choose story as the source column.',
      target: { kind: 'field', id: 'text-source-columns' },
      advance: 'next-button',
    },
    {
      id: 'enter-verification-question',
      title: 'Ask what needs verification',
      instruction: 'Enter: What specific claim in this story most needs independent verification, and what record or source could verify it?',
      target: { kind: 'field', id: 'field-question' },
      advance: 'next-button',
    },
    {
      id: 'name-next-check',
      title: 'Name the answer column',
      instruction: 'Set Save to to next_check.',
      target: { kind: 'field', id: 'field-output-answer' },
      advance: 'next-button',
    },
    {
      id: 'run-ask',
      title: 'Generate follow-up questions',
      instruction: 'Click Run.',
      target: { kind: 'field', id: 'generated-action-run' },
      expected: 'Each story receives a concrete suggestion for the next reporting check.',
      advance: 'click-target',
    },
    {
      id: 'review-ai-triage',
      title: 'Review, sort, and verify',
      instruction: 'Compare summary, topic, and next_check with the original story. Treat every generated value as a lead to review.',
      target: { kind: 'completed-run', target: { kind: 'element', id: 'grid' } },
      expected: 'The initially raw sheet now supports scanning, sorting, and source-by-source review.',
      advance: 'next-button',
    },
  ],
};

export const RSS_IMPORT_WALKTHROUGH: WalkthroughDefinition = {
  id: 'rss-import',
  title: 'Import a live civic RSS feed',
  description: 'Connect the public Riverton demo feed, populate a sheet, and categorize its current items.',
  requirements: 'Requires network access to frisket-dev.github.io and, for now, a model provider for classification.',
  steps: [
    {
      id: 'open-import-tab',
      title: 'Open Data',
      instruction: 'Click Data to see the project import and export tools.',
      target: { kind: 'action-tab', id: 'data' },
      advance: 'click-target',
    },
    {
      id: 'open-import-workspace',
      title: 'Choose Import data',
      instruction: 'Click Import data to open the full import workspace.',
      target: { kind: 'command', id: 'import' },
      advance: 'click-target',
    },
    {
      id: 'choose-feed-mode',
      title: 'Choose Feed',
      instruction: 'Click Feed in the import sidebar.',
      target: { kind: 'element', id: 'import-mode-feed' },
      advance: 'click-target',
    },
    {
      id: 'enter-feed-url',
      title: 'Enter the public feed URL',
      instruction: 'Enter https://frisket-dev.github.io/frisket-samples/riverton/feed.xml',
      target: { kind: 'element', id: 'source-url' },
      advance: 'next-button',
    },
    {
      id: 'confirm-rss-kind',
      title: 'Confirm RSS',
      instruction: 'Confirm that Type is RSS.',
      target: { kind: 'element', id: 'source-kind' },
      advance: 'next-button',
    },
    {
      id: 'name-feed',
      title: 'Name the feed',
      instruction: 'Name it Riverton Dispatch RSS.',
      target: { kind: 'element', id: 'source-name' },
      advance: 'next-button',
    },
    {
      id: 'add-feed',
      title: 'Add the feed',
      instruction: 'Click Add feed.',
      target: { kind: 'element', id: 'source-create' },
      expected: 'Frisket saves the source and offers to populate it now.',
      advance: 'click-target',
    },
    {
      id: 'populate-feed',
      title: 'Fetch the current items',
      instruction: 'Click Run to poll the new source.',
      target: { kind: 'element', id: 'feed-populate-run' },
      expected: 'A new sheet is populated from the public RSS items.',
      advance: 'click-target',
    },
    {
      id: 'review-feed',
      title: 'Review the imported feed',
      instruction: 'Inspect the title and summary columns. Summary contains the full demo story body supplied by this feed, not an AI-generated summary.',
      target: { kind: 'element', id: 'grid' },
      expected: 'The imported rows retain their feed links and publication metadata.',
      advance: 'next-button',
    },
    {
      id: 'open-feed-extract',
      title: 'Open Analyze',
      instruction: 'Click Analyze to find actions that turn the incoming text into consistent labels.',
      target: { kind: 'action-tab', id: 'analyze' },
      advance: 'click-target',
    },
    {
      id: 'open-feed-classify',
      title: 'Choose Classify',
      instruction: 'Click Classify to assign one civic-news category to every feed item.',
      target: { kind: 'action', id: 'map.classify' },
      advance: 'click-target',
    },
    {
      id: 'choose-feed-classify-source',
      title: 'Categorize the story body',
      instruction: 'Choose summary as the source column. In this RSS sheet, that is where the feed stores each full story body.',
      target: { kind: 'field', id: 'classify-source-column-select' },
      advance: 'next-button',
    },
    {
      id: 'review-feed-labels',
      title: 'Choose the categories',
      instruction: {
        lead: 'Enter categories for this feed, such as',
        code: 'housing, courts, public safety, contracts, health, transit, education, environment, other',
      },
      target: { kind: 'field', id: 'classify-labels' },
      advance: 'next-button',
    },
    {
      id: 'name-feed-topic',
      title: 'Name the category column',
      instruction: {
        lead: 'Set Save to to',
        code: 'topic',
      },
      target: { kind: 'field', id: 'new-column-name' },
      advance: 'next-button',
    },
    {
      id: 'choose-feed-classify-model',
      title: 'Choose a model',
      instruction: 'Choose an available model for this classification run.',
      target: { kind: 'field', id: 'model-picker-button' },
      advance: 'next-button',
    },
    {
      id: 'run-feed-classify',
      title: 'Categorize the feed',
      instruction: 'Click Run to fill topic for every imported item.',
      target: { kind: 'field', id: 'run-button' },
      expected: 'A topic value populates beside every feed item.',
      advance: 'click-target',
    },
    {
      id: 'review-feed-topics',
      title: 'Scan the categorized feed',
      instruction: 'Compare the topic column with the original titles and story bodies. The feed is now ready to sort, filter, and review as new items arrive.',
      target: { kind: 'completed-run', target: { kind: 'element', id: 'grid' } },
      expected: 'The imported source has become a repeatable intake-and-triage workflow.',
      advance: 'next-button',
    },
  ],
};

export const COMBINE_VALUES_WALKTHROUGH: WalkthroughDefinition = {
  id: 'combine-values',
  title: 'Clean up a messy agency column',
  description: 'Find spelling, case, and whitespace variants, combine them into reviewed agency names, and verify the repaired counts.',
  requirements: 'Runs locally with Combine values; no model provider is required.',
  steps: [
    {
      id: 'open-agency-payments',
      title: 'Open Agency payments',
      instruction: 'Click Agency payments. These 16 fictional payments came from several exports that named the same agencies inconsistently.',
      target: { kind: 'sheet', id: 'Agency payments' },
      expected: 'The raw payment records appear in Grid view.',
      advance: 'click-target',
    },
    {
      id: 'inspect-agency-column',
      title: 'Inspect the agency names',
      instruction: 'Read down agency. Look for abbreviations, capitalization differences, a city prefix, and subtle leading or trailing spaces.',
      target: { kind: 'grid-column', id: 'agency' },
      expected: 'Four real agencies are fragmented across 12 exact values.',
      advance: 'next-button',
    },
    {
      id: 'open-raw-facets',
      title: 'Open Filter',
      instruction: 'Click Filter to count the exact values before cleaning them.',
      target: { kind: 'discover-tab', id: 'Facets' },
      advance: 'click-target',
    },
    {
      id: 'choose-raw-agency-facet',
      title: 'Count the raw spellings',
      instruction: 'Find the agency facet. The sidebar pre-populates it from the open sheet.',
      target: { kind: 'element', id: 'friendly-facet-agency' },
      expected: 'Filter reports 12 distinct values across 16 rows; several labels clearly refer to the same agency.',
      advance: 'next-button',
    },
    {
      id: 'review-fragmented-counts',
      title: 'See why exact counts mislead',
      instruction: 'Review the value counts. Public Works, Water, and Transit payments are split into separate buckets because case, spaces, abbreviations, and prefixes all count as differences.',
      target: { kind: 'element', id: 'facet-values-agency' },
      advance: 'next-button',
    },
    {
      id: 'open-transform',
      title: 'Open Transform',
      instruction: 'Click Transform and find the Resolve group for standardizing and combining values.',
      target: { kind: 'action-tab', id: 'transform' },
      advance: 'click-target',
    },
    {
      id: 'open-combine',
      title: 'Choose Combine values',
      instruction: 'Click Combine values. It lets you review exact source values and hand-sort genuine variants into canonical groups.',
      target: { kind: 'action', id: 'resolve.combine' },
      expected: 'The Combine values drawer opens without changing the source column.',
      advance: 'click-target',
    },
    {
      id: 'choose-agency-column',
      title: 'Clean the agency column',
      instruction: 'Choose agency as the column to combine.',
      target: { kind: 'field', id: 'resolve-combine-column-select' },
      advance: 'next-button',
    },
    {
      id: 'notice-exact-values',
      title: 'Notice the whitespace markers',
      instruction: 'The unassigned list matches values exactly. Dotted leading or trailing regions reveal spaces that a normal grid scan can miss.',
      target: { kind: 'element', id: 'resolve-combine-exact-note' },
      expected: 'All 12 distinct spellings remain available for explicit review.',
      advance: 'next-button',
    },
    {
      id: 'select-public-works',
      title: 'Select every Public Works variant',
      instruction: 'Select the five Public Works values: the standard name, the Dept. abbreviation, all caps, and both dotted whitespace variants.',
      target: { kind: 'element', id: 'resolve-combine-unassigned' },
      advance: 'next-button',
    },
    {
      id: 'group-public-works',
      title: 'Create the Public Works group',
      instruction: 'Click New bucket. The most frequent member becomes the reviewed canonical name: Public Works Department.',
      target: { kind: 'element', id: 'resolve-combine-new-bucket' },
      expected: 'Five exact values now map to one Public Works Department group.',
      advance: 'click-target',
    },
    {
      id: 'select-water-authority',
      title: 'Select every Water Authority variant',
      instruction: 'Select Water Authority, Riverton Water Authority, and water authority. The city prefix and case differ, but the payment context shows they are the same agency.',
      target: { kind: 'element', id: 'resolve-combine-unassigned' },
      advance: 'next-button',
    },
    {
      id: 'group-water-authority',
      title: 'Create the Water Authority group',
      instruction: 'Click New bucket to use Water Authority as the canonical value.',
      target: { kind: 'element', id: 'resolve-combine-new-bucket' },
      expected: 'Three exact values now map to one Water Authority group.',
      advance: 'click-target',
    },
    {
      id: 'select-transit-authority',
      title: 'Select every Transit Authority variant',
      instruction: 'Select Transit Authority, Riverton Transit Authority, and Transit authority.',
      target: { kind: 'element', id: 'resolve-combine-unassigned' },
      advance: 'next-button',
    },
    {
      id: 'group-transit-authority',
      title: 'Create the Transit Authority group',
      instruction: 'Click New bucket to use Transit Authority as the canonical value.',
      target: { kind: 'element', id: 'resolve-combine-new-bucket' },
      expected: 'The footer now reads 11 values to 3 groups, 1 kept, and 16 rows to agency_clean.',
      advance: 'click-target',
    },
    {
      id: 'keep-unmatched-values',
      title: 'Keep values that need no repair',
      instruction: 'Leave Values not grouped on keep original. Parks Department is already clean, so it should pass through unchanged.',
      target: { kind: 'field', id: 'resolve-combine-remainder-policy' },
      advance: 'next-button',
    },
    {
      id: 'apply-agency-groups',
      title: 'Apply the reviewed groups',
      instruction: 'Click Apply groups. The default agency_clean output preserves agency as source evidence.',
      target: { kind: 'field', id: 'resolve-apply' },
      expected: 'A new agency_clean column is written for all 16 payments.',
      advance: 'click-target',
    },
    {
      id: 'review-clean-column',
      title: 'Compare raw and clean values',
      instruction: 'Scan agency beside agency_clean. Every reviewed variant has a canonical value, while the original export text remains intact.',
      target: { kind: 'completed-run', target: { kind: 'grid-column', id: 'agency_clean' } },
      advance: 'next-button',
    },
    {
      id: 'reopen-clean-facets',
      title: 'Return to Filter',
      instruction: 'Click Filter again to verify the payoff with exact counts.',
      target: { kind: 'discover-tab', id: 'Facets' },
      advance: 'click-target',
    },
    {
      id: 'choose-clean-agency-facet',
      title: 'Count the canonical names',
      instruction: 'Open the new agency_clean facet in the sidebar.',
      target: { kind: 'element', id: 'facet-header-agency_clean' },
      expected: 'The 12 raw spellings collapse to four reviewed agencies.',
      advance: 'click-target',
    },
    {
      id: 'verify-clean-counts',
      title: 'Verify the repaired totals',
      instruction: 'Confirm the final counts: Public Works Department 6, Water Authority 4, Transit Authority 4, and Parks Department 2.',
      target: { kind: 'element', id: 'facet-values-agency_clean' },
      expected: 'Grouping and filtering now operate on four meaningful agencies instead of 12 accidental spellings.',
      advance: 'next-button',
    },
  ],
};

export const MULTILINGUAL_NAMES_WALKTHROUGH: WalkthroughDefinition = {
  id: 'multilingual-names',
  title: 'Standardize a multilingual name list',
  description: 'Turn names written in several scripts into one consistent value for grouping and matching.',
  requirements: 'Runs locally with the bundled Transliterate and Substitute actions; no model provider is required.',
  steps: [
    {
      id: 'open-multilingual-names',
      title: 'Open Multilingual names',
      instruction: 'Click Multilingual names. These ten records refer to the same fictional person but came from sources using different scripts and spelling conventions.',
      target: { kind: 'sheet', id: 'Multilingual names' },
      expected: 'The raw records appear in Grid view.',
      advance: 'click-target',
    },
    {
      id: 'inspect-written-name',
      title: 'Inspect the source spellings',
      instruction: 'Read down name_as_written. Notice Cyrillic, Arabic, Greek, Japanese, accented Latin, capitalization, and whitespace differences. Keep this source column unchanged for reference.',
      target: { kind: 'grid-column', id: 'name_as_written' },
      expected: 'The values are visibly related, but exact grouping or joining would treat them as different names.',
      advance: 'next-button',
    },
    {
      id: 'open-transform',
      title: 'Open Transform',
      instruction: 'Click Transform and find the Language group with translation and transliteration tools.',
      target: { kind: 'action-tab', id: 'transform' },
      advance: 'click-target',
    },
    {
      id: 'open-transliterate',
      title: 'Choose Transliterate to Latin script',
      instruction: 'Click Transliterate to Latin script. Transliteration changes scripts; it does not translate meaning or decide whether two people are the same.',
      target: { kind: 'action', id: 'frisket.transliterate.transliterate' },
      expected: 'The local plugin action opens.',
      advance: 'click-target',
    },
    {
      id: 'choose-name-source',
      title: 'Choose the original name column',
      instruction: 'Choose name_as_written as the Text column.',
      target: { kind: 'field', id: 'field-text' },
      advance: 'next-button',
    },
    {
      id: 'run-transliterate',
      title: 'Transliterate every name',
      instruction: 'Click Run. Frisket converts each name to Latin script locally.',
      target: { kind: 'field', id: 'run-button' },
      expected: 'latin_text populates for all ten records.',
      advance: 'click-target',
    },
    {
      id: 'review-transliteration',
      title: 'Review the Latin-script results',
      instruction: 'Compare latin_text with name_as_written. Every value is now readable in Latin script, but variants such as Aleksandr, Alexander, case, initials, and spacing still remain.',
      target: { kind: 'completed-run', target: { kind: 'grid-column', id: 'latin_text' } },
      expected: 'Transliteration solved the script difference without pretending it solved identity resolution.',
      advance: 'next-button',
    },
    {
      id: 'return-to-transform',
      title: 'Return to Transform',
      instruction: 'Click Transform and return to the Resolve group for the second cleanup step.',
      target: { kind: 'action-tab', id: 'transform' },
      advance: 'click-target',
    },
    {
      id: 'open-substitute',
      title: 'Choose Substitute values',
      instruction: 'Click Substitute values to review each distinct spelling and map it to a canonical value.',
      target: { kind: 'action', id: 'resolve.substitute' },
      expected: 'The substitution review drawer opens.',
      advance: 'click-target',
    },
    {
      id: 'choose-latin-column',
      title: 'Use the transliterated column',
      instruction: 'Choose latin_text. Frisket loads the distinct values and their counts without changing the source.',
      target: { kind: 'field', id: 'resolve-substitute-column' },
      advance: 'next-button',
    },
    {
      id: 'map-canonical-name',
      title: 'Map every variant to one name',
      instruction: {
        lead: 'For each listed value, enter the same canonical spelling in its Maps to box:',
        code: 'Alexander Petrov',
        explanation: 'This reviewed mapping is the identity decision. Transliteration alone cannot safely make it for you.',
      },
      target: { kind: 'element', id: 'resolve-substitute-table' },
      expected: 'Every distinct Latin-script variant points to Alexander Petrov.',
      advance: 'next-button',
    },
    {
      id: 'apply-substitution',
      title: 'Apply the reviewed mapping',
      instruction: 'Click Apply to write the default latin_text_clean column.',
      target: { kind: 'field', id: 'resolve-apply' },
      expected: 'The reviewed canonical value is written without overwriting either source column.',
      advance: 'click-target',
    },
    {
      id: 'review-standardized-names',
      title: 'Compare raw, transliterated, and canonical values',
      instruction: 'Scan name_as_written, latin_text, and latin_text_clean together. You now have source fidelity, a searchable transliteration, and one reviewed value suitable for grouping or joining.',
      target: { kind: 'completed-run', target: { kind: 'grid-column', id: 'latin_text_clean' } },
      expected: 'All ten rows share Alexander Petrov in the canonical column while the original evidence remains intact.',
      advance: 'next-button',
    },
  ],
};

export const LOCAL_MODEL_LAB_ENDPOINT_NAME = 'Local model lab server';

export const LOCAL_MODEL_LAB_WALKTHROUGH: WalkthroughDefinition = {
  id: 'local-model-lab',
  title: 'Learn what a small local model can — and cannot — do',
  description: 'Connect a named local model server, run a dependable labeling task, then compare a harder reasoning task with an answer key.',
  requirements: 'Requires Ollama and an AI call mode that permits live requests. The recommended qwen3:0.6b model is a 523 MB download.',
  editions: ['local', 'team'],
  steps: [
    {
      id: 'open-local-model-lab',
      title: 'Open Small model lab',
      instruction: 'Click Small model lab. It contains easy notices, harder evidence puzzles, and editor-written answers for comparison.',
      target: { kind: 'sheet', id: 'Small model lab' },
      expected: 'Six synthetic records appear in Grid view.',
      advance: 'click-target',
    },
    {
      id: 'inspect-easy-notices',
      title: 'Start with the easy notices',
      instruction: 'Read easy_notice and expected_notice_type. Each short notice clearly identifies itself as a meeting, inspection, or contract.',
      target: { kind: 'grid-column', id: 'easy_notice' },
      expected: 'The answer is explicit enough for a very small model.',
      advance: 'next-button',
    },
    {
      id: 'open-local-analyze',
      title: 'Open Analyze',
      instruction: 'Click Analyze to find the row-by-row model actions.',
      target: { kind: 'action-tab', id: 'analyze' },
      advance: 'click-target',
    },
    {
      id: 'open-local-classify',
      title: 'Choose Classify',
      instruction: 'Click Classify. We will use its model picker to connect the local server before running.',
      target: { kind: 'action', id: 'map.classify' },
      advance: 'click-target',
    },
    {
      id: 'choose-easy-source-preview',
      title: 'Choose the easy source',
      instruction: 'Choose easy_notice so the action reads only the short notice text.',
      target: { kind: 'field', id: 'classify-source-column-select' },
      advance: 'next-button',
    },
    {
      id: 'open-local-account-menu',
      title: 'Open the account menu',
      instruction: 'Open the account menu so you can configure the model server before choosing the LLM engine.',
      target: { kind: 'element', id: 'chrome-account' },
      advance: 'click-target',
    },
    {
      id: 'open-local-account-settings',
      title: 'Open account settings',
      instruction: 'Click Account settings. Frisket remembers this project so you can return after setup.',
      target: { kind: 'element', id: 'account-settings' },
      advance: 'click-target',
    },
    {
      id: 'configure-local-providers',
      title: 'Open AI providers',
      instruction: 'Choose AI providers to add and probe a named local server.',
      target: { kind: 'element', id: 'settings-nav-personal-ai-providers' },
      advance: 'click-target',
    },
    {
      id: 'open-local-server-form',
      title: 'Add a local server',
      instruction: 'Click Add local server. Every server gets its own stable identity, even when two machines offer the same model name.',
      target: { kind: 'element', id: 'local-endpoint-add' },
      advance: 'click-target',
    },
    {
      id: 'name-local-server',
      title: 'Name this server',
      instruction: { lead: 'Set Name to', code: LOCAL_MODEL_LAB_ENDPOINT_NAME },
      target: { kind: 'field', id: 'local-endpoint-add-name' },
      advance: 'next-button',
    },
    {
      id: 'point-at-local-server',
      title: 'Enter the server URL',
      instruction: {
        lead: 'Install and start Ollama on the machine that will run the model, then set URL to',
        code: 'http://localhost:11434',
        explanation: 'If Ollama runs on another machine, enter that reachable origin instead.',
        learnMore: { label: 'Download Ollama', href: 'https://ollama.com/download' },
      },
      target: { kind: 'field', id: 'local-endpoint-add-origin' },
      advance: 'next-button',
    },
    {
      id: 'save-local-server',
      title: 'Save this endpoint',
      instruction: 'Click Add server. Frisket assigns this origin an immutable endpoint ID so future runs keep routing to the machine you selected.',
      target: { kind: 'field', id: 'local-endpoint-add-submit' },
      expected: 'A Local model lab server row appears with its own reachability, authentication, and download controls.',
      advance: 'click-target',
    },
    {
      id: 'verify-local-reachability',
      title: 'Check the server status',
      instruction: 'Confirm the new endpoint row says reachable. If it does not, check where Ollama is running; changing its URL means creating a new endpoint.',
      target: {
        kind: 'local-endpoint',
        label: LOCAL_MODEL_LAB_ENDPOINT_NAME,
        part: 'row',
      },
      advance: 'next-button',
    },
    {
      id: 'install-small-model',
      title: 'Install the small model',
      instruction: {
        lead: 'If qwen3:0.6b is not listed, enable in-app downloads and use the Download button, or run',
        code: 'ollama pull qwen3:0.6b',
        explanation: 'The in-app option is deliberately opt-in because it writes hundreds of megabytes to the model-server machine.',
        learnMore: { label: 'View the model in Ollama', href: 'https://ollama.com/library/qwen3:0.6b' },
      },
      target: {
        kind: 'local-endpoint',
        label: LOCAL_MODEL_LAB_ENDPOINT_NAME,
        part: 'guidance',
      },
      expected: 'qwen3:0.6b appears under Local model lab server after the download and a Recheck.',
      advance: 'next-button',
    },
    {
      id: 'return-to-local-project',
      title: 'Return to the project',
      instruction: 'Return to the sample project. Settings are saved for this workspace.',
      target: { kind: 'element', id: 'settings-return-project' },
      advance: 'click-target',
    },
    {
      id: 'reopen-local-analyze',
      title: 'Reopen Analyze',
      instruction: 'Click Analyze to restart the easy labeling action after leaving Settings.',
      target: { kind: 'action-tab', id: 'analyze' },
      advance: 'click-target',
    },
    {
      id: 'reopen-local-classify',
      title: 'Reopen Classify',
      instruction: 'Click Classify.',
      target: { kind: 'action', id: 'map.classify' },
      advance: 'click-target',
    },
    {
      id: 'choose-easy-source',
      title: 'Read the easy notice',
      instruction: 'Choose easy_notice as the source column.',
      target: { kind: 'field', id: 'classify-source-column-select' },
      advance: 'next-button',
    },
    {
      id: 'choose-local-llm',
      title: 'Find the runner picker',
      instruction: 'Use Run with to choose the Ollama model for this action.',
      target: { kind: 'field', id: 'model-picker-button' },
      advance: 'next-button',
    },
    {
      id: 'set-easy-labels',
      title: 'Use three explicit labels',
      instruction: {
        lead: 'Enter',
        code: 'meeting, inspection, contract',
      },
      target: { kind: 'field', id: 'classify-labels' },
      expected: 'The category schema now limits the model to the three known answers.',
      advance: 'next-button',
    },
    {
      id: 'name-local-label',
      title: 'Name the generated label',
      instruction: { lead: 'Set Save to to', code: 'small_model_label' },
      target: { kind: 'field', id: 'new-column-name' },
      advance: 'next-button',
    },
    {
      id: 'choose-small-model',
      title: 'Choose qwen3:0.6b',
      instruction: 'Open the model picker and choose qwen3:0.6b under Local model lab server. The saved model ID includes that endpoint, so an identical tag on another server stays distinct.',
      target: { kind: 'field', id: 'model-picker-button' },
      advance: 'next-button',
    },
    {
      id: 'run-easy-local-task',
      title: 'Run the easy task locally',
      instruction: 'Click Run. The endpoint-qualified local model has no provider charge in Frisket; access to the machine itself is controlled by its operator.',
      target: { kind: 'field', id: 'run-button' },
      expected: 'small_model_label populates for all six rows.',
      advance: 'click-target',
    },
    {
      id: 'review-easy-local-task',
      title: 'Compare with the easy answer key',
      instruction: 'Compare small_model_label with expected_notice_type. This constrained task should be a comfortable fit for the tiny model.',
      target: { kind: 'completed-run', target: { kind: 'grid-column', id: 'small_model_label' } },
      expected: 'The generated labels match, or any mistake is immediately visible.',
      advance: 'next-button',
    },
    {
      id: 'open-hard-analyze',
      title: 'Return to Analyze',
      instruction: 'Click Analyze for a task that requires tracking several rules and decoys.',
      target: { kind: 'action-tab', id: 'analyze' },
      advance: 'click-target',
    },
    {
      id: 'open-hard-ask',
      title: 'Choose Ask',
      instruction: 'Click Ask to pose the same reasoning question to every challenge.',
      target: { kind: 'action', id: 'map.ask' },
      advance: 'click-target',
    },
    {
      id: 'choose-hard-source',
      title: 'Read the evidence puzzle',
      instruction: 'Choose challenge_text as the source column.',
      target: { kind: 'field', id: 'text-source-columns' },
      advance: 'next-button',
    },
    {
      id: 'enter-hard-question',
      title: 'Require every constraint',
      instruction: {
        lead: 'Enter',
        code: 'Apply every rule in the text. Return the single requested ID or result, followed by one sentence explaining it.',
      },
      target: { kind: 'field', id: 'field-question' },
      advance: 'next-button',
    },
    {
      id: 'name-hard-answer',
      title: 'Name the model answer',
      instruction: { lead: 'Set Save to to', code: 'small_model_answer' },
      target: { kind: 'field', id: 'field-output-answer' },
      advance: 'next-button',
    },
    {
      id: 'confirm-hard-model',
      title: 'Choose the same small model',
      instruction: 'Choose qwen3:0.6b under Local model lab server again. Actions keep separate drafts, so make the endpoint explicit before comparing results.',
      target: { kind: 'field', id: 'model-picker-button' },
      advance: 'next-button',
    },
    {
      id: 'run-hard-local-task',
      title: 'Run the harder task',
      instruction: 'Click Run. This local run starts without an unknown-provider-cost dialog; the answer key is deliberately not included in the model input.',
      target: { kind: 'field', id: 'generated-action-run' },
      expected: 'small_model_answer populates beside the authored challenge_answer.',
      advance: 'click-target',
    },
    {
      id: 'review-local-limit',
      title: 'See the capability boundary',
      instruction: 'Compare small_model_answer with challenge_answer one row at a time. Count exact matches, inspect confident mistakes, and decide whether this task needs a larger local model, a cloud model, or a deterministic rule.',
      target: { kind: 'completed-run', target: { kind: 'grid-column', id: 'small_model_answer' } },
      expected: 'The easy task and hard task now have visible, reviewable evidence instead of a vague impression that the model worked.',
      advance: 'next-button',
    },
  ],
};

export const WALKTHROUGHS = [
  REGEX_EXTRACT_WALKTHROUGH,
  LAWSUIT_DOCUMENT_WALKTHROUGH,
  COUNCIL_AUDIO_WALKTHROUGH,
  CIVIC_AI_TRIAGE_WALKTHROUGH,
  RSS_IMPORT_WALKTHROUGH,
  COMBINE_VALUES_WALKTHROUGH,
  MULTILINGUAL_NAMES_WALKTHROUGH,
  LOCAL_MODEL_LAB_WALKTHROUGH,
] as const;
