#!/bin/sh
# Discovers project.db files and supervises Litestream replication to S3 or a
# local replica. Missing replica configuration is fatal.
set -eu

DATA_DIR="${FRISKET_DATA_DIR:-/data}"
GENERATED="${LITESTREAM_GENERATED_CONFIG:-/tmp/litestream.gen.yml}"
RESCAN_INTERVAL="${LITESTREAM_RESCAN_INTERVAL:-60}"
PREFIX="${LITESTREAM_PREFIX:-prod}"
REPLICA_DIR="${LITESTREAM_REPLICA_DIR:-}"
MAX_CONSECUTIVE_CRASHES="${LITESTREAM_MAX_CONSECUTIVE_CRASHES:-3}"
CRASH_BACKOFF="${LITESTREAM_CRASH_BACKOFF:-5}"

log() { echo "litestream-entrypoint: $*" >&2; }

if [ -z "$REPLICA_DIR" ]; then
  if [ -z "${LITESTREAM_BUCKET:-}" ]; then
    log "FATAL: no replica target configured."
    log "  Set LITESTREAM_BUCKET (+ endpoint/region/keys) for s3 replication,"
    log "  or LITESTREAM_REPLICA_DIR for a local file:// replica (drill/dev)."
    log "  Refusing to start so a misconfig is never mistaken for a no-op backup."
    exit 1
  fi
  if [ -z "${LITESTREAM_ACCESS_KEY_ID:-}" ] || [ -z "${LITESTREAM_SECRET_ACCESS_KEY:-}" ]; then
    log "FATAL: LITESTREAM_BUCKET is set but S3 credentials are incomplete."
    log "  Set both LITESTREAM_ACCESS_KEY_ID and LITESTREAM_SECRET_ACCESS_KEY,"
    log "  or set LITESTREAM_REPLICA_DIR to use the local file replica path."
    exit 1
  fi
  if [ -z "${LITESTREAM_ENDPOINT:-}" ]; then
    log "FATAL: LITESTREAM_BUCKET is set but LITESTREAM_ENDPOINT is empty."
    log "  Production uses Cloudflare R2, e.g. https://<ACCOUNT_ID>.r2.cloudflarestorage.com."
    log "  Local S3-compatible drills must also set an explicit endpoint."
    exit 1
  fi
fi

emit_replica() {
  project="$1"
  if [ -n "$REPLICA_DIR" ]; then
    cat <<YAML
      - type: file
        path: ${REPLICA_DIR}/${project}
        sync-interval: ${LITESTREAM_SYNC_INTERVAL:-1s}
YAML
  else
    cat <<YAML
      - type: s3
        bucket: ${LITESTREAM_BUCKET}
        path: frisket/${PREFIX}/projects/${project}
        endpoint: ${LITESTREAM_ENDPOINT:-}
        region: ${LITESTREAM_REGION:-auto}
        force-path-style: true
        access-key-id: ${LITESTREAM_ACCESS_KEY_ID:-}
        secret-access-key: ${LITESTREAM_SECRET_ACCESS_KEY:-}
        retention: ${LITESTREAM_RETENTION:-168h}
        retention-check-interval: ${LITESTREAM_RETENTION_CHECK_INTERVAL:-1h}
        snapshot-interval: ${LITESTREAM_SNAPSHOT_INTERVAL:-1h}
        sync-interval: ${LITESTREAM_SYNC_INTERVAL:-10s}
YAML
  fi
}

list_projects() {
  # Preserve nested paths so distinct bundles cannot share a replica entry.
  find "$DATA_DIR" -mindepth 2 -type f -name project.db 2>/dev/null \
    | sed -e "s#^${DATA_DIR}/##" -e 's#/project.db$##' \
    | sort
}

# Write through a sibling file and rename atomically; a visible header-only
# config can make restore silently replicate nothing. Returns 1 when empty.
generate_config() {
  projects="$(list_projects)"
  scratch="${GENERATED}.tmp.$$"
  old_umask="$(umask)"
  umask 077
  {
    echo "# GENERATED by scripts/release/litestream-entrypoint.sh — do not edit."
    echo "# One explicit dbs entry per discovered project.db (globs are a"
    echo "# silent no-op under litestream 0.3/0.5). Regenerated on rescan."
    echo "dbs:"
  } > "$scratch"
  umask "$old_umask"
  chmod 600 "$scratch"

  count=0
  for project in $projects; do
    [ -n "$project" ] || continue
    {
      # Keep ${FRISKET_DATA_DIR} literal for restore into a fresh data root.
      echo "  - path: \${FRISKET_DATA_DIR}/${project}/project.db"
      echo "    replicas:"
      emit_replica "$project"
    } >> "$scratch"
    count=$((count + 1))
  done

  if [ "$count" -eq 0 ]; then
    # Empty discovery may be transient; retain the last valid config. The caller
    # stops Litestream until a non-empty scan succeeds.
    rm -f "$scratch"
    return 1
  fi

  mv -f "$scratch" "$GENERATED"
  log "generated config for $count project db(s): $(echo "$projects" | tr '\n' ' ')"
  return 0
}

fingerprint() {
  if command -v sha256sum >/dev/null 2>&1; then
    list_projects | sha256sum | cut -d' ' -f1
  elif command -v shasum >/dev/null 2>&1; then
    list_projects | shasum -a 256 | cut -d' ' -f1
  else
    log "FATAL: no sha256sum or shasum binary found for project-set fingerprinting"
    exit 1
  fi
}

LS_PID=""
CONSECUTIVE_CRASHES=0
start_litestream() {
  log "starting: litestream replicate -config $GENERATED"
  litestream replicate -config "$GENERATED" &
  LS_PID=$!
}
stop_litestream() {
  [ -n "$LS_PID" ] || return 0
  kill "$LS_PID" 2>/dev/null || true
  wait "$LS_PID" 2>/dev/null || true
  LS_PID=""
}
handle_litestream_crash() {
  status=0
  if wait "$LS_PID" 2>/dev/null; then
    status=0
  else
    status=$?
  fi
  LS_PID=""
  CONSECUTIVE_CRASHES=$((CONSECUTIVE_CRASHES + 1))
  log "WARNING: litestream child exited unexpectedly with status ${status} (${CONSECUTIVE_CRASHES}/${MAX_CONSECUTIVE_CRASHES})"
  if [ "$CONSECUTIVE_CRASHES" -ge "$MAX_CONSECUTIVE_CRASHES" ]; then
    log "FATAL: litestream child crashed ${CONSECUTIVE_CRASHES} consecutive time(s); exiting instead of restarting forever"
    exit 1
  fi
  log "backing off ${CRASH_BACKOFF}s before restarting litestream"
  sleep "$CRASH_BACKOFF"
  start_litestream
}

trap 'log "shutting down"; stop_litestream; rm -f "${GENERATED}.tmp.$$"; exit 0' INT TERM

LAST_FP=""
while true; do
  if generate_config; then
    FP="$(fingerprint)"
    if [ "$FP" != "$LAST_FP" ]; then
      [ -n "$LS_PID" ] && { log "project db set changed; restarting litestream"; stop_litestream; }
      CONSECUTIVE_CRASHES=0
      start_litestream
      LAST_FP="$FP"
    elif [ -n "$LS_PID" ] && ! kill -0 "$LS_PID" 2>/dev/null; then
      # Bound crash restarts so persistent failure becomes visible.
      handle_litestream_crash
    elif [ -n "$LS_PID" ]; then
      CONSECUTIVE_CRASHES=0
    fi
  else
    if [ -n "$LS_PID" ]; then
      log "all project dbs disappeared; stopping litestream until one returns"
      stop_litestream
      LAST_FP=""
    fi
    log "no project.db found under ${DATA_DIR} yet; waiting (rescan ${RESCAN_INTERVAL}s)"
  fi
  sleep "$RESCAN_INTERVAL"
done
