// Generated by scripts/dev/sync_ocr_engine_catalog.py from the canonical
// OCR_ENGINE_TABLE (frisket.contracts.actions.schemas._engines) and
// OCR_VISION_ENGINES (frisket.server.action_catalog_hints). Do not edit
// by hand.
import type { EngineOption } from '../api/types';

export const OCR_ENGINE_FALLBACK_GENERATED = [
  {
    "id": "rapidocr",
    "label": "RapidOCR (local, default)",
    "tier": "local",
    "available": false,
    "error": "Action catalog unavailable"
  },
  {
    "id": "tesseract",
    "label": "Tesseract OCR (local, system binary)",
    "tier": "local",
    "available": false,
    "error": "Action catalog unavailable"
  },
  {
    "id": "paddleocr-vl",
    "label": "PaddleOCR-VL document VLM (sidecar)",
    "tier": "sidecar",
    "available": false,
    "error": "Action catalog unavailable"
  },
  {
    "id": "dots.mocr",
    "label": "dots.mocr multilingual document parser (sidecar)",
    "tier": "sidecar",
    "available": false,
    "error": "Action catalog unavailable"
  },
  {
    "id": "pp-ocrv6",
    "label": "PP-OCRv6 fast text OCR (sidecar)",
    "tier": "sidecar",
    "available": false,
    "error": "Action catalog unavailable"
  },
  {
    "id": "glm-ocr",
    "label": "GLM-OCR 0.9B multilingual OCR (sidecar)",
    "tier": "sidecar",
    "available": false,
    "error": "Action catalog unavailable"
  },
  {
    "id": "surya2",
    "label": "Surya 2 document OCR (local sidecar)",
    "tier": "sidecar",
    "available": false,
    "error": "Action catalog unavailable"
  },
  {
    "id": "openai/gpt-4.1-mini",
    "label": "OpenAI GPT-4.1 mini vision OCR (remote)",
    "tier": "hosted",
    "billable": true,
    "available": false,
    "error": "Action catalog unavailable"
  },
  {
    "id": "gemini/gemini-3.5-flash",
    "label": "Gemini 3.5 Flash vision OCR (remote)",
    "tier": "hosted",
    "billable": true,
    "available": false,
    "error": "Action catalog unavailable"
  },
  {
    "id": "openrouter/minimax/minimax-m3",
    "label": "MiniMax M3 document OCR (OpenRouter)",
    "tier": "hosted",
    "billable": true,
    "available": false,
    "error": "Action catalog unavailable"
  },
  {
    "id": "datalab",
    "label": "Datalab hosted OCR (hosted, pay-per-call)",
    "tier": "hosted",
    "billable": true,
    "available": false,
    "error": "Action catalog unavailable"
  }
] satisfies EngineOption[];
