// Generated by scripts/dev/sync_model_catalog.py from the canonical
// src/frisket/ai/llm/model_catalog.json. Do not edit by hand.
import type { ModelOption } from '../api/types';

export const GENERATED_MODEL_OPTIONS = [
  {
    "id": "gemini/gemini-3.5-flash-lite",
    "label": "Gemini 3.5 Flash-Lite — fast/cheap (default)"
  },
  {
    "id": "anthropic/claude-haiku-4-5",
    "label": "Claude Haiku 4.5 — fastest"
  },
  {
    "id": "anthropic/claude-sonnet-4-6",
    "label": "Claude Sonnet 4.6 — balanced"
  },
  {
    "id": "anthropic/claude-sonnet-5",
    "label": "Claude Sonnet 5 — latest balanced"
  },
  {
    "id": "anthropic/claude-opus-4-8",
    "label": "Claude Opus 4.8 — complex work"
  },
  {
    "id": "anthropic/claude-fable-5",
    "label": "Claude Fable 5 — frontier"
  },
  {
    "id": "openai/gpt-5-mini",
    "label": "GPT-5 mini — economical"
  },
  {
    "id": "openai/gpt-5",
    "label": "GPT-5 — previous generation"
  },
  {
    "id": "openai/gpt-5.6-luna",
    "label": "GPT-5.6 Luna — fast/economical"
  },
  {
    "id": "openai/gpt-5.6-terra",
    "label": "GPT-5.6 Terra — balanced"
  },
  {
    "id": "openai/gpt-5.6-sol",
    "label": "GPT-5.6 Sol — frontier"
  },
  {
    "id": "gemini/gemini-3.1-flash-lite",
    "label": "Gemini 3.1 Flash-Lite — high throughput"
  },
  {
    "id": "gemini/gemini-3.5-flash",
    "label": "Gemini 3.5 Flash — balanced"
  },
  {
    "id": "gemini/gemini-3.6-flash",
    "label": "Gemini 3.6 Flash — latest multimodal"
  },
  {
    "id": "gemini/gemini-3.1-pro-preview",
    "label": "Gemini 3.1 Pro — complex work (preview)"
  },
  {
    "id": "openrouter/qwen/qwen3-8b",
    "label": "Qwen 3 8B — open weights; requests go to OpenRouter"
  },
  {
    "id": "openrouter/qwen/qwen3-vl-8b-instruct",
    "label": "Qwen3-VL 8B — open vision"
  },
  {
    "id": "openrouter/qwen/qwen3-vl-32b-instruct",
    "label": "Qwen3-VL 32B — open vision"
  },
  {
    "id": "openrouter/z-ai/glm-5.3-flash",
    "label": "GLM 5.3 Flash — open vision"
  },
  {
    "id": "openrouter/moonshotai/kimi-k3",
    "label": "Kimi K3 — open vision"
  },
  {
    "id": "openrouter/xiaomi/mimo-v2.5",
    "label": "MiMo V2.5 — open vision"
  },
  {
    "id": "openrouter/minimax/minimax-m3",
    "label": "MiniMax M3 — hosted multimodal OCR via OpenRouter"
  }
] satisfies ModelOption[];
