"""Import-light contracts shared by transcription gateways and workers."""

from .contract import (
    CONTRACT_VERSION,
    TRANSCRIBE_ENDPOINT,
    AdapterRegistration,
    DiarizationMode,
    EngineProbe,
    GatewayTranscriptionResponse,
    SpeakerHint,
    TranscribeOptionName,
    TranscribeOptions,
    TranscribeResult,
    TranscribeSegment,
    TranscribeWord,
    TranscriptionAdapter,
    TranscriptionEngineDescriptor,
    TranscriptionErrorEnvelope,
    TranscriptionError,
    TranscriptionInputError,
    TranscriptionOptionSupport,
    WorkerCapabilities,
    WorkerTranscriptionResponse,
)

__all__ = [
    "CONTRACT_VERSION",
    "TRANSCRIBE_ENDPOINT",
    "AdapterRegistration",
    "DiarizationMode",
    "EngineProbe",
    "GatewayTranscriptionResponse",
    "SpeakerHint",
    "TranscribeOptionName",
    "TranscribeOptions",
    "TranscribeResult",
    "TranscribeSegment",
    "TranscribeWord",
    "TranscriptionAdapter",
    "TranscriptionEngineDescriptor",
    "TranscriptionErrorEnvelope",
    "TranscriptionError",
    "TranscriptionInputError",
    "TranscriptionOptionSupport",
    "WorkerCapabilities",
    "WorkerTranscriptionResponse",
]
