// Workbench contribution-id constants. Shared between the workspace view-model
// hook and the workspace region components, so they live in one module both
// import.
import {
  COPILOT_DESCRIPTOR,
  EMBEDDINGS_DESCRIPTOR,
  FRIENDLY_FILTERS_DESCRIPTOR,
  EVIDENCE_VIEW_DESCRIPTOR,
  GRAPH_NEIGHBORHOOD_VIEW_DESCRIPTOR,
  MENTIONS_DESCRIPTOR,
  NOTIFICATIONS_DESCRIPTOR,
  SAVED_VIEWS_DESCRIPTOR,
  SEARCH_DESCRIPTOR,
  SOURCES_DESCRIPTOR,
  SOURCE_HEALTH_VIEW_DESCRIPTOR,
  WATCHES_DESCRIPTOR,
} from '../workbench/descriptors';

export const EMPTY_MISSING_CONTRIBUTION_IDS: string[] = [];
export const EVIDENCE_CONTRIBUTION_ID = EVIDENCE_VIEW_DESCRIPTOR.id;
export const GRAPH_NEIGHBORHOOD_CONTRIBUTION_ID = GRAPH_NEIGHBORHOOD_VIEW_DESCRIPTOR.id;
export const SOURCE_HEALTH_CONTRIBUTION_ID = SOURCE_HEALTH_VIEW_DESCRIPTOR.id;
// The leftSidebar panel contribution ids, split between the interim strip
// and the Discover panel.
export const SEARCH_CONTRIBUTION_ID = SEARCH_DESCRIPTOR.id;
export const COPILOT_CONTRIBUTION_ID = COPILOT_DESCRIPTOR.id;
export const FRIENDLY_FILTERS_CONTRIBUTION_ID = FRIENDLY_FILTERS_DESCRIPTOR.id;
export const MENTIONS_CONTRIBUTION_ID = MENTIONS_DESCRIPTOR.id;
export const SOURCES_CONTRIBUTION_ID = SOURCES_DESCRIPTOR.id;
export const SAVED_VIEWS_CONTRIBUTION_ID = SAVED_VIEWS_DESCRIPTOR.id;
export const WATCHES_CONTRIBUTION_ID = WATCHES_DESCRIPTOR.id;
export const NOTIFICATIONS_CONTRIBUTION_ID = NOTIFICATIONS_DESCRIPTOR.id;
export const EMBEDDINGS_CONTRIBUTION_ID = EMBEDDINGS_DESCRIPTOR.id;
