#!/usr/bin/env python3
"""Regenerate frontend HTTP contracts from the real composition OpenAPI.

Usage:
    uv run python scripts/ci/gen_http_contracts.py
    uv run python scripts/ci/gen_http_contracts.py --check
    uv run python scripts/ci/gen_http_contracts.py --edition open
"""

from __future__ import annotations

import argparse
import json
import sys
import tempfile
from collections.abc import Sequence
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "src"
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from frisket.actions.registry import ACTION_REGISTRY  # noqa: E402
from frisket.contracts.http.typescript import (  # noqa: E402
    openapi_contract_artifact,
    render_typescript_declaration,
    render_typescript_module,
)
from scripts.ci.export_web_openapi import export_real_compositions  # noqa: E402


OPEN_FRONTEND_HTTP_CONTRACT_ARTIFACT = (
    ROOT / "web" / "src" / "generated" / "openHttpContracts.ts"
)
ACTION_TYPES_ARTIFACT = ROOT / "web" / "src" / "generated" / "actionTypes.ts"
ACTION_UI_TYPES_SOURCE = ROOT / "src" / "frisket" / "data" / "action_ui.d.ts"
ACTION_UI_TYPES_ARTIFACT = ROOT / "web" / "src" / "generated" / "actionUI.ts"


def _open_artifact() -> dict[str, object]:
    """Build the public wire projection from disposable real compositions."""

    with tempfile.TemporaryDirectory(prefix="frisket-http-contracts-") as raw:
        document = export_real_compositions(Path(raw) / "state")
    return openapi_contract_artifact(document)


def render_action_types() -> str:
    from frisket.ops.entities import _LABEL_ALIASES

    params_models = {
        action.action_id: action.definition.run.params_model
        for action in sorted(ACTION_REGISTRY.actions, key=lambda item: item.action_id)
    }
    declarations = "\n\n".join(
        render_typescript_declaration(
            model.model_json_schema(), type_name=model.__name__
        )
        for model in dict.fromkeys(params_models.values())
    )
    mappings = "\n".join(
        f"  {action_id!r}: {model.__name__};"
        for action_id, model in params_models.items()
    )
    json_value = (
        "export type JsonValue = null | boolean | number | string | "
        "JsonValue[] | { [key: string]: JsonValue };\n\n"
        if "JsonValue" in declarations
        else ""
    )
    return (
        "// Generated by scripts/ci/gen_http_contracts.py. Do not edit.\n\n"
        f"{json_value}"
        f"{declarations}\n\n"
        "export interface GeneratedActionParams {\n"
        f"{mappings}\n"
        "}\n\n"
        "export const ENTITY_TYPE_ALIASES: Readonly<Record<string, string>> = "
        f"{json.dumps(_LABEL_ALIASES, sort_keys=True, indent=2)};\n"
    )


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit nonzero if generated frontend HTTP contract artifacts are stale",
    )
    parser.add_argument(
        "--edition",
        choices=("open",),
        default="open",
        help="generate the independently distributable open projection",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="write to an explicit path instead of the edition's committed artifact",
    )
    args = parser.parse_args(argv)

    artifact = _open_artifact()
    rendered = render_typescript_module(artifact)
    outputs = [(args.output or OPEN_FRONTEND_HTTP_CONTRACT_ARTIFACT, rendered)]
    if args.output is None:
        outputs.append((ACTION_TYPES_ARTIFACT, render_action_types()))
        outputs.append(
            (
                ACTION_UI_TYPES_ARTIFACT,
                "// Generated by scripts/ci/gen_http_contracts.py. Do not edit.\n\n"
                + ACTION_UI_TYPES_SOURCE.read_text(encoding="utf-8"),
            )
        )

    if args.check:
        stale = [
            target
            for target, content in outputs
            if not target.exists() or target.read_text(encoding="utf-8") != content
        ]
        if stale:
            for target in stale:
                sys.stderr.write(
                    f"{target} is stale; regenerate frontend contracts and commit "
                    "the diff.\n"
                )
            return 1
        for target, _content in outputs:
            print(f"{target} is fresh")
        return 0

    for target, content in outputs:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
