#!/usr/bin/env python3
"""Generate the browser's pre-catalog OCR engine fallback from the backend
roster — the OCR-list twin of sync_model_catalog.py.

Canonical sources: `OCR_ENGINE_TABLE` (frisket.contracts.actions.schemas._engines,
tier/label/billable for the symbolic local/sidecar/datalab engines) and
`OCR_VISION_ENGINES` (frisket.server.action_catalog_hints, id/label/billable
for the hosted LLM-vision engines dispatched by provider/model id rather than
by symbolic engine name). Both feed `_recipe_engines`'s "ocr" branch, so this
script and that function can never see different data.

`ROSTER_ORDER` pins the display order to match `_recipe_engines`'s return
list exactly (a projector parity test elsewhere pins dots.mocr to index 3).
Every OCR runtime is optional, so every fallback entry is unavailable until
the live catalog confirms that runtime — see engineCatalog.ts's
OCR_ENGINE_FALLBACK doc comment for the "honest pre-catalog placeholder"
rationale.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from frisket.contracts.actions.schemas._engines import OCR_ENGINE_TABLE
from frisket.server.action_catalog_hints import OCR_VISION_ENGINES

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "web/src/actions/engineCatalog.generated.ts"

ROSTER_ORDER = [
    "rapidocr",
    "tesseract",
    "paddleocr-vl",
    "dots.mocr",
    "pp-ocrv6",
    "glm-ocr",
    "surya2",
    "openai/gpt-4.1-mini",
    "gemini/gemini-3.5-flash",
    "openrouter/minimax/minimax-m3",
    "datalab",
]

PRE_CATALOG_ERROR = "Action catalog unavailable"


def render() -> str:
    table = {decl.id: decl for decl in OCR_ENGINE_TABLE}
    vision = {entry["id"]: entry for entry in OCR_VISION_ENGINES}
    # ROSTER_ORDER must equal the canonical table/vision union so generated
    # fallback entries cannot silently disappear.
    canonical = set(table) | set(vision)
    if set(ROSTER_ORDER) != canonical:
        missing = sorted(canonical - set(ROSTER_ORDER))
        stale = sorted(set(ROSTER_ORDER) - canonical)
        raise SystemExit(
            "ROSTER_ORDER is out of sync with the canonical OCR engine "
            f"sources (missing: {missing or 'none'}; stale: {stale or 'none'}); "
            "update ROSTER_ORDER in scripts/dev/sync_ocr_engine_catalog.py"
        )
    engines = []
    for engine_id in ROSTER_ORDER:
        if engine_id in table:
            decl = table[engine_id]
            label, tier, billable = decl.label, decl.tier, decl.billable
        else:
            entry = vision[engine_id]
            label, tier, billable = entry["label"], "hosted", entry["billable"]
        item: dict[str, object] = {"id": engine_id, "label": label, "tier": tier}
        if billable:
            item["billable"] = True
        item["available"] = False
        item["error"] = PRE_CATALOG_ERROR
        engines.append(item)
    body = json.dumps(engines, indent=2, ensure_ascii=False)
    return (
        "// Generated by scripts/dev/sync_ocr_engine_catalog.py from the canonical\n"
        "// OCR_ENGINE_TABLE (frisket.contracts.actions.schemas._engines) and\n"
        "// OCR_VISION_ENGINES (frisket.server.action_catalog_hints). Do not edit\n"
        "// by hand.\n"
        "import type { EngineOption } from '../api/types';\n\n"
        f"export const OCR_ENGINE_FALLBACK_GENERATED = {body} satisfies EngineOption[];\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = render()
    if args.check:
        if not OUT.exists() or OUT.read_text() != output:
            raise SystemExit(
                "web OCR engine fallback is stale; run scripts/dev/sync_ocr_engine_catalog.py"
            )
        print(f"up to date: {OUT.relative_to(ROOT)}")
        return
    OUT.write_text(output)
    print(f"wrote {OUT.relative_to(ROOT)}: {len(ROSTER_ORDER)} engines")


if __name__ == "__main__":
    main()
