#!/usr/bin/env python3
"""Generate the browser's offline/hosted fallback from the canonical catalog."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "src/frisket/ai/llm/model_catalog.json"
OUT = ROOT / "web/src/actions/modelCatalog.generated.ts"


def render() -> str:
    catalog = json.loads(SOURCE.read_text())
    providers = catalog["providers"]
    # The first option is the form default; group the rest by provider. Export
    # only id and label because the server owns estimates and the 402 gate.
    flattened = [
        {"id": f"{provider}/{entry['id']}", "label": entry["label"]}
        for provider, entries in providers.items()
        if provider != "ollama"
        for entry in entries
    ]
    default_index = next(
        (i for i, entry in enumerate(flattened) if "(default)" in entry["label"]),
        0,
    )
    flattened.insert(0, flattened.pop(default_index))
    body = json.dumps(flattened, indent=2, ensure_ascii=False)
    return (
        "// Generated by scripts/dev/sync_model_catalog.py from the canonical\n"
        "// src/frisket/ai/llm/model_catalog.json. Do not edit by hand.\n"
        "import type { ModelOption } from '../api/types';\n\n"
        f"export const GENERATED_MODEL_OPTIONS = {body} satisfies ModelOption[];\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = render()
    if args.check:
        if not OUT.exists() or OUT.read_text() != output:
            raise SystemExit(
                "web model fallback is stale; run scripts/dev/sync_model_catalog.py"
            )
        print(f"up to date: {OUT.relative_to(ROOT)}")
        return
    OUT.write_text(output)
    catalog = json.loads(SOURCE.read_text())
    count = sum(
        len(entries)
        for provider, entries in catalog["providers"].items()
        if provider != "ollama"
    )
    print(f"wrote {OUT.relative_to(ROOT)}: {count} models")


if __name__ == "__main__":
    main()
